### ISSUE TITLE
glslang::limits is private, causing developers unable to create new ShaderInput since we cannot use ResourceLimits

### ISSUE THREAD

**Issue by GeForceLegend** [SnowflakePowered/glslang-rs#1]
https://github.com/SnowflakePowered/glslang-rs/blob/master/glslang/src/lib.rs#L4

Similarly, `glslang::ctypes` is private too, so we cannot using `glslang::ctypes::ShaderStage`, which means 2 params of those 3 in `ShaderInput::new()` is unable to get. I'm not sure if there is any more similar issue, plz check carefully before publish next version.

**Comment by chyyran** [comment]
Thanks for finding that! I'll push a new version after work later today, however keep in mind that I have a lot of API changes in store and pushed the 0.1.x release late at night so I could have something usable for librashader. I'll be polishing the crate up and releasing 0.2.x in the next couple of days/weeks.

**Comment by chyyran** [comment]
In the meanwhile you can use the equivalent in glslang_sys which are just aliases to ctypes.

**Comment by chyyran** [comment]
fixed in 0.2.3.

versions prior to 0.2.3 have soundness issues so they got yanked
